// export const All_EVENT_REQUEST = "All_EVENT_REQUEST";
// export const All_EVENT_SUCCESS = "All_EVENT_SUCCESS";
// export const All_EVENT_FAIL = "All_EVENT_FAIL";


// export const NEW_EVENT_REQUEST = "NE_EVENT_REQUEST";
// export const NEW_EVENT_SUCCESS = "NEW_EVENT_SUCCESS";
// export const NEW_EVENT_RESET = "NEW_EVENT_RESET";
// export const NEW_EVENT_FAIL = "NEW_EVENT_FAIL";

// export const DELETE_EVENT_REQUEST = "UPCOMING_EVENT_REQUEST";
// export const DELETE_EVENT_SUCCESS = "UPCOMING_EVENT_SUCCESS";
// export const DELETE_EVENT_RESET = "UPCOMING_EVENT_RESET";
// export const DELETE_EVENT_FAIL = "UPCOMING_EVENT_FAIL";

// export const EVENT_DETAILS_REQUEST = "EVENT_DETAILS_REQUEST";
// export const EVENT_DETAILS_SUCCESS = "EVENT_DETAILS_SUCCESS";
// export const EVENT_DETAILS_FAIL = "EVENT_DETAILS_FAIL";

// export const CLEAR_ERROR = "CLEAR_ERROR";