export const All_QUESTION_REQUEST = "All_QUESTION_REQUEST";
export const All_QUESTION_SUCCESS = "All_QUESTION_SUCCESS";
export const All_QUESTION_FAIL = "All_QUESTION_FAIL";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";
export const DELETE_QUESTION_RESET = "DELETE_QUESTION_RESET";

export const NEW_QUESTION_REQUEST = "NEW_QUESTION_REQUEST";
export const NEW_QUESTION_SUCCESS = "NEW_QUESTION_SUCCESS";
export const NEW_QUESTION_RESET = "NEW_QUESTION_RESET";
export const NEW_QUESTION_FAIL = "NEW_QUESTION_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";