// export const All_SPONSER_REQUEST = "All_SPONSER_REQUEST";
// export const All_SPONSER_SUCCESS = "All_SPONSER_SUCCESS";
// export const All_SPONSER_FAIL = "All_SPONSER_FAIL";


// export const NEW_SPONSER_REQUEST = "NEW_SPONSER_REQUEST";
// export const NEW_SPONSER_SUCCESS = "NEW_SPONSER_SUCCESS";
// export const NEW_SPONSER_RESET = "NEW_SPONSER_RESET";
// export const NEW_SPONSER_FAIL = "NEW_SPONSER_FAIL";

// export const DELETE_SPONSER_REQUEST = "DELETE_SPONSER_REQUEST";
// export const DELETE_SPONSER_SUCCESS = "DELETE_SPONSER_SUCCESS";
// export const DELETE_SPONSER_RESET = "DELETE_SPONSER_RESET";
// export const DELETE_SPONSER_FAIL = "DELETE_SPONSER_FAIL";


// export const CLEAR_ERROR = "CLEAR_ERROR";