// export const All_UPCOMING_EVENT_REQUEST = "All_UPCOMING_EVENT_REQUEST";
// export const All_UPCOMING_EVENT_SUCCESS = "All_UPCOMING_EVENT_SUCCESS";
// export const All_UPCOMING_EVENT_FAIL = "All_UPCOMING_EVENT_FAIL";


// export const NEW_UPCOMING_EVENT_REQUEST = "NEW_UPCOMING_EVENT_REQUEST";
// export const NEW_UPCOMING_EVENT_SUCCESS = "NEW_UPCOMING_EVENT_SUCCESS";
// export const NEW_UPCOMING_EVENT_RESET = "NEW_UPCOMING_EVENT_RESET";
// export const NEW_UPCOMING_EVENT_FAIL = "NEW_UPCOMING_EVENT_FAIL";

// export const DELETE_UPCOMING_EVENT_REQUEST = "DELETE_UPCOMING_EVENT_REQUEST";
// export const DELETE_UPCOMING_EVENT_SUCCESS = "DELETE_UPCOMING_EVENT_SUCCESS";
// export const DELETE_UPCOMING_EVENT_RESET = "DELETE_UPCOMING_EVENT_RESET";
// export const DELETE_UPCOMING_EVENT_FAIL = "DELETE_UPCOMING_EVENT_FAIL";

// export const UPCOMING_EVENT_DETAILS_REQUEST = "UPCOMING_EVENT_DETAILS_REQUEST";
// export const UPCOMING_EVENT_DETAILS_SUCCESS = "UPCOMING_EVENT_DETAILS_SUCCESS";
// export const UPCOMING_EVENT_DETAILS_FAIL = "UPCOMING_EVENT_DETAILS_FAIL";

// export const CLEAR_ERROR = "CLEAR_ERROR";